### ISSUE TITLE
Add hook to Cannon world instance

### ISSUE THREAD

**Issue by nevernotsean** [react-spring/use-cannon#15]
With RTF, there is a "useThree" hook thats lets us reach into a ThreeJS instance, it would be very handy to have something similar to the Cannon world instance. We could clearForces as needed, raycast bodies and getMaterials for re-use.

**Comment by drcmda** [comment]
the problem is that the worker lives in a sandbox, there is no way you could access the actual world object, unless you're building a bridge via postmessage. and if you have cannon in both threads they would be two different instances (and double the bundlesize).

cannon on the main thread for sure is the easiest way, but it's so expensive. main thread only has 5-10ms per frame to spare, that's not much with threejs rendering and everything else going on.

**Comment by nevernotsean** [comment]
Ah I see, that makes sense! We should keep things as inexpensive as possible, otherwise physics can quickly drag an app down.

I've never had the need to use clearForces myself, so maybe we can add that as needed. Other methods are better left to the worker to manage, honestly.

**Comment by drcmda** [comment]
it may even be a blessing when we decide to switch the engine for something smaller/faster. with an abstraction that may just be possible.

**Comment by nevernotsean** [comment]
closing, providing the cannon world will be too expensive, better to abstract Cannon.World as needed
