### ISSUE TITLE
Add other Primitive Shapes

### ISSUE THREAD

**Issue by nevernotsean** [react-spring/use-cannon#3]
Right now use-cannon only supports Box and Plane. Should add Sphere, Tri-mesh, Cylinder, etc.
Entire list of shapes here: https://github.com/drcmda/cannon-es/tree/master/src/shapes

**Comment by drcmda** [comment]
yes, that would be great. do you think the current api is good enough? some primitives need further arguments, using "args" for now.

**Comment by nevernotsean** [comment]
I think for now just args work great for now, removes any weird abstractions. 
I could see some merit in abstracting the HeightField and ConvexPolyhedron arguments, but I've never used them before. Will do some testing of those!

**Comment by stockHuman** [comment]
Just want to add that I sneaked in a `mesh` parameter with my ConvexPolyhedron commit. It should contain Three.Geometry vertex and face data for cannon to convert and understand. 

Mesh is perhaps too ambiguous a name, and we could pass the two required arrays within `args`.

---
On another note, Tri-meshes have particularly poor physics in Cannon, only being able to interact with spheres and planes. I don't know how useful it would be to build out support if it turns out to be at all challenging.

**Comment by drcmda** [comment]
should we maybe add more hooks? then it could all be typesafe:

```jsx
import { useBox, usePlane, useSphere, useInstancedBox } from 'use-cannon'
```

im thinking that types could be the hardest part to get right, im already struggling with the api as loose as it's defined

**Comment by drcmda** [comment]
i've started a new branch: https://github.com/react-spring/use-cannon/pull/8/files

**Comment by nevernotsean** [comment]
Looks like these are all added! closing...
